# Generated by Django 3.2.8 on 2022-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featuredproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
